sudo: required
services:
  - docker

before_install:
  - docker build -t karanotts/screengrab -f Dockerfile.dev .

script:
  - docker run -e CI=true karanotts/screengrab npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "screengrab"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-315853667188"
  bucket_path: "screengrab"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"