language: python
sudo: required
services:
  - docker

before_install:
  - docker build -t karanotts/screengrab -f Dockerfile .

install:
  - pip install requirements.txt

script: 
  - python -m unittest